
services:
  postgresql:
    image: 
      postgres:latest
    environment:
      POSTGRES_PASSWORD: your_password
      POSTGRES_USER: your_user
      POSTGRES_DB: your_database
    volumes:
      - /path/to/postgresql-persistence:/bitnami/postgresql
    ports:
      - 5432:5432

#   docker-compose up
#   docker-compose down
